
# Screen
SCREEN_SIZE = 800
LEFT_BORDER = -200
RIGHT_BORDER = 1000
UPPER_BORDER = -200
LOWER_BORDER = 1000

# Player
PLAYER_SIZE = 50
PLAYER_SPEED = 10
PLAYER_SHOOT_COOLDOWN = 10
PLAYER_INVINCIBILITY = 60
PLAYER_KNOCKBACK = 25
SPAWN_TIMER = 20

# Enemy
ENEMY_SIZE = 50
ENEMY_SPEED = 8
ENEMY_DAMAGE = 10
ENEMY_RANDOM_DIRECTION_TIME = 30
ENEMY_DEATH_TIME = 30
MAX_ENEMIES = 30

# Tiles
TILE_SIZE = 200

# Projectile
PROJECTILE_SIZE = 15
PROJECTILE_SPEED = 25

# Powerup
POWERUP_SIZE = 25

